language: python
python: [2.7, 3.4, 3.5, 3.6]
env:
- FIXTURE_PATH=/tmp/schema_fixture/
install:
- pip install tox-travis
- mkdir -p "$HOME/bin"
- curl -o "$HOME/bin/nirum" https://nightly-builds.nirum.org/travis-builds/nirum-linux-x86_64
- chmod +x "$HOME/bin/nirum"
script:
- tox -e buildfixture
- tox
- tox -e docs
- '[[ "$TRAVIS_TAG" = "" ]] || [[ "$TRAVIS_TAG" = "$(python setup.py --version)" ]]'
- |
  if git show --format=%B --quiet "${TRAVIS_PULL_REQUEST_SHA:-${TRAVIS_TAG:-${TRAVIS_COMMIT}}}" \
     | grep '\[changelog skip\]' > /dev/null; then
    echo "Skip changelog checker..."
  elif [[ "$TRAVIS_TAG" != "" ]]; then
    ! grep -i "to be released" CHANGES.rst
  else
    [[ "$(git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep CHANGES\.rst)" != "" ]]
  fi
